import { SubPost } from '@prisma/client'
import { CutRuleName } from './types'

/** Retrieves the Publicodes rule name corresponding to a given SubPost, if it exists */
export function getPublicodesTarget(subPost: SubPost): CutRuleName | undefined {
  return SUBPOST_TO_RULENAME[subPost]
}

/** Indicates whether a given SubPost has a mapping to a Publicodes rule name */
export function hasPublicodesMapping(subPost: SubPost): boolean {
  return SUBPOST_TO_RULENAME[subPost] !== undefined
}

const SUBPOST_TO_RULENAME: Record<SubPost, CutRuleName | undefined> = {
  // CUT
  Batiment: undefined,
  Equipe: undefined,
  Energie: undefined,
  ActivitesDeBureau: undefined,
  MobiliteSpectateurs: undefined,
  EquipesRecues: undefined,
  MaterielTechnique: undefined,
  AutreMateriel: undefined,
  Achats: undefined,
  Fret: undefined,
  Electromenager: undefined,
  DechetsOrdinaires: 'déchets . ordinaires',
  DechetsExceptionnels: 'déchets . exceptionnels',
  MaterielDistributeurs: undefined,
  MaterielCinema: undefined,
  CommunicationDigitale: undefined,
  CaissesEtBornes: undefined,

  // Autres
  CombustiblesFossiles: undefined,
  CombustiblesOrganiques: undefined,
  ReseauxDeChaleurEtDeVapeur: undefined,
  ReseauxDeFroid: undefined,
  Electricite: undefined,
  Agriculture: undefined,
  EmissionsLieesAuChangementDAffectationDesSolsCas: undefined,
  EmissionsLieesALaProductionDeFroid: undefined,
  EmissionsLieesAuxProcedesIndustriels: undefined,
  AutresEmissionsNonEnergetiques: undefined,
  MetauxPlastiquesEtVerre: undefined,
  PapiersCartons: undefined,
  MateriauxDeConstruction: undefined,
  ProduitsChimiquesEtHydrogene: undefined,
  NourritureRepasBoissons: undefined,
  MatiereDestineeAuxEmballages: undefined,
  AutresIntrants: undefined,
  BiensEtMatieresEnApprocheMonetaire: undefined,
  AchatsDeServices: undefined,
  UsagesNumeriques: undefined,
  ServicesEnApprocheMonetaire: undefined,
  DechetsDEmballagesEtPlastiques: undefined,
  DechetsOrganiques: undefined,
  DechetsOrduresMenageres: 'déchets . ordinaires . ordures ménagères',
  DechetsDangereux: undefined,
  DechetsBatiments: undefined,
  DechetsFuitesOuEmissionsNonEnergetiques: undefined,
  EauxUsees: undefined,
  AutresDechets: undefined,
  FretEntrant: undefined,
  FretInterne: undefined,
  FretSortant: undefined,
  DeplacementsDomicileTravail: undefined,
  DeplacementsProfessionnels: undefined,
  DeplacementsVisiteurs: undefined,
  Batiments: undefined,
  AutresInfrastructures: undefined,
  Equipements: undefined,
  Informatique: undefined,
  UtilisationEnResponsabilite: undefined,
  UtilisationEnDependance: undefined,
  InvestissementsFinanciersRealises: undefined,
  ConsommationDEnergieEnFinDeVie: undefined,
  TraitementDesDechetsEnFinDeVie: undefined,
  FuitesOuEmissionsNonEnergetiques: undefined,
  TraitementDesEmballagesEnFinDeVie: undefined,
  FroidEtClim: undefined,
  ActivitesAgricoles: undefined,
  ActivitesIndustrielles: undefined,
  DeplacementsDomicileTravailSalaries: undefined,
  DeplacementsDomicileTravailBenevoles: undefined,
  DeplacementsDansLeCadreDUneMissionAssociativeSalaries: undefined,
  DeplacementsDansLeCadreDUneMissionAssociativeBenevoles: undefined,
  DeplacementsDesBeneficiaires: undefined,
  DeplacementsFabricationDesVehicules: undefined,
  Entrant: undefined,
  Interne: undefined,
  Sortant: undefined,
  TransportFabricationDesVehicules: undefined,
  RepasPrisParLesSalaries: undefined,
  RepasPrisParLesBenevoles: undefined,
  UtilisationEnResponsabiliteConsommationDeBiens: undefined,
  UtilisationEnResponsabiliteConsommationNumerique: undefined,
  UtilisationEnResponsabiliteConsommationDEnergie: undefined,
  UtilisationEnResponsabiliteFuitesEtAutresConsommations: undefined,
  UtilisationEnDependanceConsommationDeBiens: undefined,
  UtilisationEnDependanceConsommationNumerique: undefined,
  UtilisationEnDependanceConsommationDEnergie: undefined,
  UtilisationEnDependanceFuitesEtAutresConsommations: undefined,
  TeletravailSalaries: undefined,
  TeletravailBenevoles: undefined,
  EquipementsDesSalaries: undefined,
  ParcInformatiqueDesSalaries: undefined,
  EquipementsDesBenevoles: undefined,
  ParcInformatiqueDesBenevoles: undefined,
} as const
