services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: bilancarbone
      POSTGRES_PASSWORD: bilancarbone
    ports:
      - '5432:5432'
    restart: unless-stopped
  maildev:
    image: maildev/maildev
    ports:
      - '1080:1080'
      - '1025:1025'
    restart: unless-stopped
