export enum EngagementActionTargets {
  TEAM_PROJECT = 'TEAM_PROJECT',
  DIRECTION = 'DIRECTION',
  OTHER_INTERNAL_COLLABORATORS = 'OTHER_INTERNAL_COLLABORATORS',
  FURNISHERS = 'FURNISHERS',
  CLIENTS = 'CLIENTS',
  PARTNERS = 'PARTNERS',
  OTHERS_EXTERNAL = 'OTHERS_EXTERNAL',
}

export enum EngagementActionSteps {
  AT_LAUNCH_OF_APPROACH = 'AT_LAUNCH_OF_APPROACH',
  AT_LAUNCH_OF_DATA_COLLECTION = 'AT_LAUNCH_OF_DATA_COLLECTION',
  DURING_DATA_COLLECTION = 'DURING_DATA_COLLECTION',
  BEFORE_RESULTS_RESTITUTION = 'BEFORE_RESULTS_RESTITUTION',
  AT_LAUNCH_OF_TRANSITION_PLAN_CONSTRUCTION = 'AT_LAUNCH_OF_TRANSITION_PLAN_CONSTRUCTION',
  DURING_TRANSITION_PLAN_CONSTRUCTION = 'DURING_TRANSITION_PLAN_CONSTRUCTION',
  IN_SUMMARY_OF_APPROACH = 'IN_SUMMARY_OF_APPROACH',
}
