import { EmissionFactorPartType, ExportRule, SubPost } from '@prisma/client'

export const begesRules = [
  {
    subPost: SubPost.CombustiblesFossiles,
    operated: '1.1',
    notOperated: '6.1',
    held: '1.1',
    notHeldSimpleRent: '4.4',
    notHeldOther: '6.1',
  },
  {
    subPost: SubPost.CombustiblesFossiles,
    type: EmissionFactorPartType.Amont,
    operated: '4.1',
    notOperated: '6.1',
    held: '4.1',
    notHeldSimpleRent: '4.4',
    notHeldOther: '6.1',
  },
  {
    subPost: SubPost.CombustiblesFossiles,
    type: EmissionFactorPartType.Combustion,
    operated: '1.1',
    notOperated: '6.1',
    held: '1.1',
    notHeldSimpleRent: '4.4',
    notHeldOther: '6.1',
  },
  {
    subPost: SubPost.CombustiblesFossiles,
    type: EmissionFactorPartType.CombustionALaCentrale,
    operated: '1.1',
    notOperated: '6.1',
    held: '1.1',
    notHeldSimpleRent: '4.4',
    notHeldOther: '6.1',
  },
  {
    subPost: SubPost.CombustiblesFossiles,
    type: EmissionFactorPartType.EmissionsFugitives,
    operated: '1.4',
    notOperated: '6.1',
    held: '1.4',
    notHeldSimpleRent: '4.4',
    notHeldOther: '6.1',
  },
  {
    subPost: SubPost.CombustiblesFossiles,
    type: EmissionFactorPartType.Fabrication,
    operated: '4.1',
    notOperated: '6.1',
    held: '4.1',
    notHeldSimpleRent: '4.4',
    notHeldOther: '6.1',
  },
  {
    subPost: SubPost.CombustiblesFossiles,
    type: EmissionFactorPartType.Fuites,
    operated: '1.4',
    notOperated: '6.1',
    held: '1.4',
    notHeldSimpleRent: '4.4',
    notHeldOther: '6.1',
  },
  {
    subPost: SubPost.CombustiblesOrganiques,
    operated: '1.1',
    notOperated: '6.1',
    held: '1.1',
    notHeldSimpleRent: '4.4',
    notHeldOther: '6.1',
  },
  {
    subPost: SubPost.CombustiblesOrganiques,
    type: EmissionFactorPartType.Amont,
    operated: '4.1',
    notOperated: '6.1',
    held: '4.1',
    notHeldSimpleRent: '4.4',
    notHeldOther: '6.1',
  },
  {
    subPost: SubPost.CombustiblesOrganiques,
    type: EmissionFactorPartType.Combustion,
    operated: '1.1',
    notOperated: '6.1',
    held: '1.1',
    notHeldSimpleRent: '4.4',
    notHeldOther: '6.1',
  },
  {
    subPost: SubPost.CombustiblesOrganiques,
    type: EmissionFactorPartType.CombustionALaCentrale,
    operated: '1.1',
    notOperated: '6.1',
    held: '1.1',
    notHeldSimpleRent: '4.4',
    notHeldOther: '6.1',
  },
  {
    subPost: SubPost.CombustiblesOrganiques,
    type: EmissionFactorPartType.EmissionsFugitives,
    operated: '1.4',
    notOperated: '6.1',
    held: '1.4',
    notHeldSimpleRent: '4.4',
    notHeldOther: '6.1',
  },
  {
    subPost: SubPost.CombustiblesOrganiques,
    type: EmissionFactorPartType.Fabrication,
    operated: '4.1',
    notOperated: '6.1',
    held: '4.1',
    notHeldSimpleRent: '4.4',
    notHeldOther: '6.1',
  },
  {
    subPost: SubPost.CombustiblesOrganiques,
    type: EmissionFactorPartType.Fuites,
    operated: '1.4',
    notOperated: '6.1',
    held: '1.4',
    notHeldSimpleRent: '4.4',
    notHeldOther: '6.1',
  },
  {
    subPost: SubPost.ReseauxDeChaleurEtDeVapeur,
    operated: '2.2',
    notOperated: '6.1',
    held: '2.2',
    notHeldSimpleRent: '4.4',
    notHeldOther: '6.1',
  },
  {
    subPost: SubPost.ReseauxDeChaleurEtDeVapeur,
    type: EmissionFactorPartType.Amont,
    operated: '4.1',
    notOperated: '6.1',
    held: '4.1',
    notHeldSimpleRent: '4.4',
    notHeldOther: '6.1',
  },
  {
    subPost: SubPost.ReseauxDeChaleurEtDeVapeur,
    type: EmissionFactorPartType.CombustionALaCentrale,
    operated: '2.2',
    notOperated: '6.1',
    held: '2.2',
    notHeldSimpleRent: '4.4',
    notHeldOther: '6.1',
  },
  {
    subPost: SubPost.ReseauxDeChaleurEtDeVapeur,
    type: EmissionFactorPartType.Pertes,
    operated: '4.1',
    notOperated: '6.1',
    held: '4.1',
    notHeldSimpleRent: '4.4',
    notHeldOther: '6.1',
  },
  {
    subPost: SubPost.ReseauxDeFroid,
    operated: '2.2',
    notOperated: '6.1',
    held: '2.2',
    notHeldSimpleRent: '4.4',
    notHeldOther: '6.1',
  },
  {
    subPost: SubPost.ReseauxDeFroid,
    type: EmissionFactorPartType.Amont,
    operated: '4.1',
    notOperated: '6.1',
    held: '4.1',
    notHeldSimpleRent: '4.4',
    notHeldOther: '6.1',
  },
  {
    subPost: SubPost.ReseauxDeFroid,
    type: EmissionFactorPartType.CombustionALaCentrale,
    operated: '2.2',
    notOperated: '6.1',
    held: '2.2',
    notHeldSimpleRent: '4.4',
    notHeldOther: '6.1',
  },
  {
    subPost: SubPost.ReseauxDeFroid,
    type: EmissionFactorPartType.Pertes,
    operated: '4.1',
    notOperated: '6.1',
    held: '4.1',
    notHeldSimpleRent: '4.4',
    notHeldOther: '6.1',
  },
  {
    subPost: SubPost.Electricite,
    operated: '2.1',
    notOperated: '6.1',
    held: '2.1',
    notHeldSimpleRent: '4.4',
    notHeldOther: '6.1',
  },
  {
    subPost: SubPost.Electricite,
    type: EmissionFactorPartType.Amont,
    operated: '4.1',
    notOperated: '6.1',
    held: '4.1',
    notHeldSimpleRent: '4.4',
    notHeldOther: '6.1',
  },
  {
    subPost: SubPost.Electricite,
    type: EmissionFactorPartType.Combustion,
    operated: '2.1',
    notOperated: '6.1',
    held: '2.1',
    notHeldSimpleRent: '4.4',
    notHeldOther: '6.1',
  },
  {
    subPost: SubPost.Electricite,
    type: EmissionFactorPartType.CombustionALaCentrale,
    operated: '2.1',
    notOperated: '6.1',
    held: '2.1',
    notHeldSimpleRent: '4.4',
    notHeldOther: '6.1',
  },
  {
    subPost: SubPost.Electricite,
    type: EmissionFactorPartType.EmissionsFugitives,
    operated: '2.1',
    notOperated: '6.1',
    held: '2.1',
    notHeldSimpleRent: '4.4',
    notHeldOther: '6.1',
  },
  {
    subPost: SubPost.Electricite,
    type: EmissionFactorPartType.TransportEtDistribution,
    operated: '4.1',
    notOperated: '6.1',
    held: '4.1',
    notHeldSimpleRent: '4.4',
    notHeldOther: '6.1',
  },
  {
    subPost: SubPost.Agriculture,
    operatedProcedeed: '1.3',
    operatedFugitive: '1.4',
    notOperated: '6.1',
    heldProcedeed: '1.3',
    heldFugitive: '1.4',
    notHeldSimpleRent: '4.4',
    notHeldOther: '6.1',
  },
  {
    subPost: SubPost.EmissionsLieesAuChangementDAffectationDesSolsCas,
    operatedProcedeed: '1.5',
    operatedFugitive: '1.5',
    notOperated: '1.5',
    held: '1.5',
    notHeldSimpleRent: '4.4',
    notHeldOther: '6.1',
  },
  {
    subPost: SubPost.EmissionsLieesALaProductionDeFroid,
    operatedProcedeed: '1.4',
    operatedFugitive: '1.4',
    notOperated: '1.4',
    held: '1.4',
    notHeldSimpleRent: '4.4',
    notHeldOther: '6.1',
  },
  {
    subPost: SubPost.EmissionsLieesAuxProcedesIndustriels,
    operatedProcedeed: '1.3',
    operatedFugitive: '1.3',
    notOperated: '1.3',
    held: '1.3',
    notHeldSimpleRent: '4.4',
    notHeldOther: '6.1',
  },
  {
    subPost: SubPost.AutresEmissionsNonEnergetiques,
    operatedProcedeed: '1.3',
    operatedFugitive: '1.4',
    notOperated: '6.1',
    heldProcedeed: '1.3',
    heldFugitive: '1.4',
    notHeldSimpleRent: '4.4',
    notHeldOther: '6.1',
  },
  { subPost: SubPost.MetauxPlastiquesEtVerre, operated: '4.1', held: '4.1' },
  { subPost: SubPost.PapiersCartons, operated: '4.1', held: '4.1' },
  { subPost: SubPost.MateriauxDeConstruction, operated: '4.1', held: '4.1' },
  { subPost: SubPost.ProduitsChimiquesEtHydrogene, operated: '4.1', held: '4.1' },
  { subPost: SubPost.NourritureRepasBoissons, operated: '4.1', held: '4.1' },
  { subPost: SubPost.MatiereDestineeAuxEmballages, operated: '4.1', held: '4.1' },
  { subPost: SubPost.AutresIntrants, operated: '4.1', held: '4.1' },
  { subPost: SubPost.BiensEtMatieresEnApprocheMonetaire, operated: '4.1', held: '4.1' },
  { subPost: SubPost.AchatsDeServices, operated: '4.5', held: '4.5' },
  { subPost: SubPost.UsagesNumeriques, operated: '4.5', held: '4.5' },
  { subPost: SubPost.ServicesEnApprocheMonetaire, operated: '4.5', held: '4.5' },
  {
    subPost: SubPost.FretEntrant,
    operated: '1.2',
    notOperatedSupported: '3.1',
    notOperatedNotSupported: '3.2',
    held: '1.2',
    notHeldSupported: '3.1',
    notHeldNotSupported: '3.2',
  },
  {
    subPost: SubPost.FretEntrant,
    type: EmissionFactorPartType.Amont,
    operated: '4.1',
    notOperatedSupported: '3.1',
    notOperatedNotSupported: '3.2',
    held: '4.1',
    notHeldSupported: '3.1',
    notHeldNotSupported: '3.2',
  },
  {
    subPost: SubPost.FretEntrant,
    type: EmissionFactorPartType.Combustion,
    operated: '1.2',
    notOperatedSupported: '3.1',
    notOperatedNotSupported: '3.2',
    held: '1.2',
    notHeldSupported: '3.1',
    notHeldNotSupported: '3.2',
  },
  {
    subPost: SubPost.FretEntrant,
    type: EmissionFactorPartType.CombustionALaCentrale,
    operated: '2.1',
    notOperatedSupported: '3.1',
    notOperatedNotSupported: '3.2',
    held: '2.1',
    notHeldSupported: '3.1',
    notHeldNotSupported: '3.2',
  },
  {
    subPost: SubPost.FretEntrant,
    type: EmissionFactorPartType.EmissionsFugitives,
    operated: '1.4',
    notOperatedSupported: '3.1',
    notOperatedNotSupported: '3.2',
    held: '1.4',
    notHeldSupported: '3.1',
    notHeldNotSupported: '3.2',
  },
  {
    subPost: SubPost.FretEntrant,
    type: EmissionFactorPartType.Fabrication,
    operated: '4.2',
    notOperatedSupported: '3.1',
    notOperatedNotSupported: '3.2',
    held: '4.2',
    notHeldSupported: '3.1',
    notHeldNotSupported: '3.2',
  },
  {
    subPost: SubPost.FretInterne,
    operated: '1.2',
    notOperatedSupported: '3.1',
    notOperatedNotSupported: '3.2',
    held: '1.2',
    notHeldSupported: '3.1',
    notHeldNotSupported: '3.2',
  },
  {
    subPost: SubPost.FretInterne,
    type: EmissionFactorPartType.Amont,
    operated: '4.1',
    notOperatedSupported: '3.1',
    notOperatedNotSupported: '3.2',
    held: '4.1',
    notHeldSupported: '3.1',
    notHeldNotSupported: '3.2',
  },
  {
    subPost: SubPost.FretInterne,
    type: EmissionFactorPartType.Combustion,
    operated: '1.2',
    notOperatedSupported: '3.1',
    notOperatedNotSupported: '3.2',
    held: '1.2',
    notHeldSupported: '3.1',
    notHeldNotSupported: '3.2',
  },
  {
    subPost: SubPost.FretInterne,
    type: EmissionFactorPartType.CombustionALaCentrale,
    operated: '2.1',
    notOperatedSupported: '3.1',
    notOperatedNotSupported: '3.2',
    held: '2.1',
    notHeldSupported: '3.1',
    notHeldNotSupported: '3.2',
  },
  {
    subPost: SubPost.FretInterne,
    type: EmissionFactorPartType.EmissionsFugitives,
    operated: '1.4',
    notOperatedSupported: '3.1',
    notOperatedNotSupported: '3.2',
    held: '1.4',
    notHeldSupported: '3.1',
    notHeldNotSupported: '3.2',
  },
  {
    subPost: SubPost.FretInterne,
    type: EmissionFactorPartType.Fabrication,
    operated: '4.2',
    notOperatedSupported: '3.1',
    notOperatedNotSupported: '3.2',
    held: '4.2',
    notHeldSupported: '3.1',
    notHeldNotSupported: '3.2',
  },
  {
    subPost: SubPost.FretSortant,
    operated: '1.2',
    notOperatedSupported: '3.1',
    notOperatedNotSupported: '3.2',
    held: '1.2',
    notHeldSupported: '3.1',
    notHeldNotSupported: '3.2',
  },
  {
    subPost: SubPost.FretSortant,
    type: EmissionFactorPartType.Amont,
    operated: '4.1',
    notOperatedSupported: '3.1',
    notOperatedNotSupported: '3.2',
    held: '4.1',
    notHeldSupported: '3.1',
    notHeldNotSupported: '3.2',
  },
  {
    subPost: SubPost.FretSortant,
    type: EmissionFactorPartType.Combustion,
    operated: '1.2',
    notOperatedSupported: '3.1',
    notOperatedNotSupported: '3.2',
    held: '1.2',
    notHeldSupported: '3.1',
    notHeldNotSupported: '3.2',
  },
  {
    subPost: SubPost.FretSortant,
    type: EmissionFactorPartType.CombustionALaCentrale,
    operated: '2.1',
    notOperatedSupported: '3.1',
    notOperatedNotSupported: '3.2',
    held: '2.1',
    notHeldSupported: '3.1',
    notHeldNotSupported: '3.2',
  },
  {
    subPost: SubPost.FretSortant,
    type: EmissionFactorPartType.EmissionsFugitives,
    operated: '1.4',
    notOperatedSupported: '3.1',
    notOperatedNotSupported: '3.2',
    held: '1.4',
    notHeldSupported: '3.1',
    notHeldNotSupported: '3.2',
  },
  {
    subPost: SubPost.FretSortant,
    type: EmissionFactorPartType.Fabrication,
    operated: '4.2',
    notOperatedSupported: '3.1',
    notOperatedNotSupported: '3.2',
    held: '4.2',
    notHeldSupported: '3.1',
    notHeldNotSupported: '3.2',
  },
  {
    subPost: SubPost.DeplacementsDomicileTravail,
    operated: '1.2',
    notOperated: '3.3',
    held: '1.2',
    notHeldSimpleRent: '4.4',
    notHeldOther: '3.3',
  },
  {
    subPost: SubPost.DeplacementsDomicileTravail,
    type: EmissionFactorPartType.Amont,
    operated: '4.1',
    notOperated: '3.3',
    held: '4.1',
    notHeldSimpleRent: '4.4',
    notHeldOther: '3.3',
  },
  {
    subPost: SubPost.DeplacementsDomicileTravail,
    type: EmissionFactorPartType.Combustion,
    operated: '1.2',
    notOperated: '3.3',
    held: '1.2',
    notHeldSimpleRent: '4.4',
    notHeldOther: '3.3',
  },
  {
    subPost: SubPost.DeplacementsDomicileTravail,
    type: EmissionFactorPartType.CombustionALaCentrale,
    operated: '2.1',
    notOperated: '3.3',
    held: '2.1',
    notHeldSimpleRent: '4.4',
    notHeldOther: '3.3',
  },
  {
    subPost: SubPost.DeplacementsDomicileTravail,
    type: EmissionFactorPartType.EmissionsFugitives,
    operated: '1.4',
    notOperated: '3.3',
    held: '1.4',
    notHeldSimpleRent: '4.4',
    notHeldOther: '3.3',
  },
  {
    subPost: SubPost.DeplacementsDomicileTravail,
    type: EmissionFactorPartType.Fabrication,
    operated: '4.2',
    notOperated: '3.3',
    held: '4.2',
    notHeldSimpleRent: '4.4',
    notHeldOther: '3.3',
  },
  {
    subPost: SubPost.DeplacementsProfessionnels,
    operated: '1.2',
    notOperated: '3.5',
    held: '1.2',
    notHeldSimpleRent: '4.4',
    notHeldOther: '3.5',
  },
  {
    subPost: SubPost.DeplacementsProfessionnels,
    type: EmissionFactorPartType.Amont,
    operated: '4.1',
    notOperated: '3.5',
    held: '4.1',
    notHeldSimpleRent: '4.4',
    notHeldOther: '3.5',
  },
  {
    subPost: SubPost.DeplacementsProfessionnels,
    type: EmissionFactorPartType.Combustion,
    operated: '1.2',
    notOperated: '3.5',
    held: '1.2',
    notHeldSimpleRent: '4.4',
    notHeldOther: '3.5',
  },
  {
    subPost: SubPost.DeplacementsProfessionnels,
    type: EmissionFactorPartType.CombustionALaCentrale,
    operated: '2.1',
    notOperated: '3.5',
    held: '2.1',
    notHeldSimpleRent: '4.4',
    notHeldOther: '3.5',
  },
  {
    subPost: SubPost.DeplacementsProfessionnels,
    type: EmissionFactorPartType.EmissionsFugitives,
    operated: '1.4',
    notOperated: '3.5',
    held: '1.4',
    notHeldSimpleRent: '4.4',
    notHeldOther: '3.5',
  },
  {
    subPost: SubPost.DeplacementsProfessionnels,
    type: EmissionFactorPartType.Fabrication,
    operated: '4.2',
    notOperated: '3.5',
    held: '4.2',
    notHeldSimpleRent: '4.4',
    notHeldOther: '3.5',
  },
  {
    subPost: SubPost.DeplacementsVisiteurs,
    operated: '1.2',
    notOperated: '3.4',
    held: '1.2',
    notHeldSimpleRent: '4.4',
    notHeldOther: '3.4',
  },
  {
    subPost: SubPost.DeplacementsVisiteurs,
    type: EmissionFactorPartType.Amont,
    operated: '4.1',
    notOperated: '3.4',
    held: '4.1',
    notHeldSimpleRent: '4.4',
    notHeldOther: '3.4',
  },
  {
    subPost: SubPost.DeplacementsVisiteurs,
    type: EmissionFactorPartType.Combustion,
    operated: '1.2',
    notOperated: '3.4',
    held: '1.2',
    notHeldSimpleRent: '4.4',
    notHeldOther: '3.4',
  },
  {
    subPost: SubPost.DeplacementsVisiteurs,
    type: EmissionFactorPartType.CombustionALaCentrale,
    operated: '2.1',
    notOperated: '3.4',
    held: '2.1',
    notHeldSimpleRent: '4.4',
    notHeldOther: '3.4',
  },
  {
    subPost: SubPost.DeplacementsVisiteurs,
    type: EmissionFactorPartType.EmissionsFugitives,
    operated: '1.4',
    notOperated: '3.4',
    held: '1.4',
    notHeldSimpleRent: '4.4',
    notHeldOther: '3.4',
  },
  {
    subPost: SubPost.DeplacementsVisiteurs,
    type: EmissionFactorPartType.Fabrication,
    operated: '4.2',
    notOperated: '3.4',
    held: '4.2',
    notHeldSimpleRent: '4.4',
    notHeldOther: '3.4',
  },
  { subPost: SubPost.Batiments, operated: '4.2', held: '4.2', notHeldSimpleRent: '4.4', notHeldOther: '6.1' },
  { subPost: SubPost.AutresInfrastructures, operated: '4.2', held: '4.2', notHeldSimpleRent: '4.4', notHeldOther: '6.1' },
  { subPost: SubPost.Equipements, operated: '4.2', held: '4.2', notHeldSimpleRent: '4.4', notHeldOther: '6.1' },
  { subPost: SubPost.Informatique, operated: '4.2', held: '4.2', notHeldSimpleRent: '4.4', notHeldOther: '6.1' },
  { subPost: SubPost.DechetsDEmballagesEtPlastiques, operated: '4.3', held: '4.3' },
  { subPost: SubPost.DechetsOrganiques, operated: '4.3', held: '4.3' },
  { subPost: SubPost.DechetsOrduresMenageres, operated: '4.3', held: '4.3' },
  { subPost: SubPost.DechetsDangereux, operated: '4.3', held: '4.3' },
  { subPost: SubPost.DechetsBatiments, operated: '4.3', held: '4.3' },
  { subPost: SubPost.DechetsFuitesOuEmissionsNonEnergetiques, operated: '4.3', held: '4.3' },
  { subPost: SubPost.EauxUsees, operated: '4.3', held: '4.3' },
  { subPost: SubPost.AutresDechets, operated: '4.3', held: '4.3' },
  {
    subPost: SubPost.UtilisationEnResponsabilite,
    rented: '5.2',
    finalClient: '5.1',
    usedByIntermediary: '5.1',
  },
  { subPost: SubPost.InvestissementsFinanciersRealises, operated: '5.4', held: '5.4' },
  { subPost: SubPost.ConsommationDEnergieEnFinDeVie, rented: '5.2', finalClient: '5.3', usedByIntermediary: '5.3' },
  { subPost: SubPost.TraitementDesDechetsEnFinDeVie, rented: '5.2', finalClient: '5.3', usedByIntermediary: '5.3' },
  { subPost: SubPost.FuitesOuEmissionsNonEnergetiques, rented: '5.2', finalClient: '5.3', usedByIntermediary: '5.3' },
  { subPost: SubPost.TraitementDesEmballagesEnFinDeVie, rented: '5.2', finalClient: '5.3', usedByIntermediary: '5.3' },
] satisfies Partial<ExportRule>[]
