import { EmissionFactorPartType, ExportRule, SubPost } from '@prisma/client'

export const ghgpRules = [
  {
    subPost: SubPost.CombustiblesFossiles,
    operated: '1.1',
    notOperated: '3.other',
    held: '1.1',
    notHeldSimpleRent: '3.8',
    notHeldOther: '3.other',
  },
  {
    subPost: SubPost.CombustiblesFossiles,
    type: EmissionFactorPartType.Amont,
    operated: '3.3',
    notOperated: '3.other',
    held: '3.3',
    notHeldSimpleRent: '3.8',
    notHeldOther: '3.other',
  },
  {
    subPost: SubPost.CombustiblesFossiles,
    type: EmissionFactorPartType.Combustion,
    operated: '1.1',
    notOperated: '3.other',
    held: '1.1',
    notHeldSimpleRent: '3.8',
    notHeldOther: '3.other',
  },
  {
    subPost: SubPost.CombustiblesFossiles,
    type: EmissionFactorPartType.CombustionALaCentrale,
    operated: '1.1',
    notOperated: '3.other',
    held: '1.1',
    notHeldSimpleRent: '3.8',
    notHeldOther: '3.other',
  },
  {
    subPost: SubPost.CombustiblesFossiles,
    type: EmissionFactorPartType.EmissionsFugitives,
    operated: '1.4',
    notOperated: '3.other',
    held: '1.4',
    notHeldSimpleRent: '3.8',
    notHeldOther: '3.other',
  },
  {
    subPost: SubPost.CombustiblesFossiles,
    type: EmissionFactorPartType.Fabrication,
    operated: '3.3',
    notOperated: '3.other',
    held: '3.3',
    notHeldSimpleRent: '3.8',
    notHeldOther: '3.other',
  },
  {
    subPost: SubPost.CombustiblesFossiles,
    type: EmissionFactorPartType.Fuites,
    operated: '1.4',
    notOperated: '3.other',
    held: '1.4',
    notHeldSimpleRent: '3.8',
    notHeldOther: '3.other',
  },
  {
    subPost: SubPost.CombustiblesOrganiques,
    operated: '1.1',
    notOperated: '3.other',
    held: '1.1',
    notHeldSimpleRent: '3.8',
    notHeldOther: '3.other',
  },
  {
    subPost: SubPost.CombustiblesOrganiques,
    type: EmissionFactorPartType.Amont,
    operated: '3.3',
    notOperated: '3.other',
    held: '3.3',
    notHeldSimpleRent: '3.8',
    notHeldOther: '3.other',
  },
  {
    subPost: SubPost.CombustiblesOrganiques,
    type: EmissionFactorPartType.Combustion,
    operated: '1.1',
    notOperated: '3.other',
    held: '1.1',
    notHeldSimpleRent: '3.8',
    notHeldOther: '3.other',
  },
  {
    subPost: SubPost.CombustiblesOrganiques,
    type: EmissionFactorPartType.CombustionALaCentrale,
    operated: '1.1',
    notOperated: '3.other',
    held: '1.1',
    notHeldSimpleRent: '3.8',
    notHeldOther: '3.other',
  },
  {
    subPost: SubPost.CombustiblesOrganiques,
    type: EmissionFactorPartType.EmissionsFugitives,
    operated: '1.4',
    notOperated: '3.other',
    held: '1.4',
    notHeldSimpleRent: '3.8',
    notHeldOther: '3.other',
  },
  {
    subPost: SubPost.CombustiblesOrganiques,
    type: EmissionFactorPartType.Fabrication,
    operated: '3.3',
    notOperated: '3.other',
    held: '3.3',
    notHeldSimpleRent: '3.8',
    notHeldOther: '3.other',
  },
  {
    subPost: SubPost.CombustiblesOrganiques,
    type: EmissionFactorPartType.Fuites,
    operated: '1.4',
    notOperated: '3.other',
    held: '1.4',
    notHeldSimpleRent: '3.8',
    notHeldOther: '3.other',
  },
  {
    subPost: SubPost.ReseauxDeChaleurEtDeVapeur,
    operated: '2.2',
    notOperated: '3.other',
    held: '2.2',
    notHeldSimpleRent: '3.8',
    notHeldOther: '3.other',
  },
  {
    subPost: SubPost.ReseauxDeChaleurEtDeVapeur,
    type: EmissionFactorPartType.Amont,
    operated: '3.3',
    notOperated: '3.other',
    held: '3.3',
    notHeldSimpleRent: '3.8',
    notHeldOther: '3.other',
  },
  {
    subPost: SubPost.ReseauxDeChaleurEtDeVapeur,
    type: EmissionFactorPartType.CombustionALaCentrale,
    operated: '2.2',
    notOperated: '3.other',
    held: '2.2',
    notHeldSimpleRent: '3.8',
    notHeldOther: '3.other',
  },
  {
    subPost: SubPost.ReseauxDeChaleurEtDeVapeur,
    type: EmissionFactorPartType.Pertes,
    operated: '3.3',
    notOperated: '3.other',
    held: '3.3',
    notHeldSimpleRent: '3.8',
    notHeldOther: '3.other',
  },
  {
    subPost: SubPost.ReseauxDeFroid,
    operated: '2.2',
    notOperated: '3.other',
    held: '2.2',
    notHeldSimpleRent: '3.8',
    notHeldOther: '3.other',
  },
  {
    subPost: SubPost.ReseauxDeFroid,
    type: EmissionFactorPartType.Amont,
    operated: '3.3',
    notOperated: '3.other',
    held: '3.3',
    notHeldSimpleRent: '3.8',
    notHeldOther: '3.other',
  },
  {
    subPost: SubPost.ReseauxDeFroid,
    type: EmissionFactorPartType.CombustionALaCentrale,
    operated: '2.2',
    notOperated: '3.other',
    held: '2.2',
    notHeldSimpleRent: '3.8',
    notHeldOther: '3.other',
  },
  {
    subPost: SubPost.ReseauxDeFroid,
    type: EmissionFactorPartType.Pertes,
    operated: '3.3',
    notOperated: '3.other',
    held: '3.3',
    notHeldSimpleRent: '3.8',
    notHeldOther: '3.other',
  },
  {
    subPost: SubPost.Electricite,
    operated: '2.1',
    notOperated: '3.other',
    held: '2.1',
    notHeldSimpleRent: '3.8',
    notHeldOther: '3.other',
  },
  {
    subPost: SubPost.Electricite,
    type: EmissionFactorPartType.Amont,
    operated: '3.3',
    notOperated: '3.other',
    held: '3.3',
    notHeldSimpleRent: '3.8',
    notHeldOther: '3.other',
  },
  {
    subPost: SubPost.Electricite,
    type: EmissionFactorPartType.Combustion,
    operated: '2.1',
    notOperated: '3.other',
    held: '2.1',
    notHeldSimpleRent: '3.8',
    notHeldOther: '3.other',
  },
  {
    subPost: SubPost.Electricite,
    type: EmissionFactorPartType.CombustionALaCentrale,
    operated: '2.1',
    notOperated: '3.other',
    held: '2.1',
    notHeldSimpleRent: '3.8',
    notHeldOther: '3.other',
  },
  {
    subPost: SubPost.Electricite,
    type: EmissionFactorPartType.EmissionsFugitives,
    operated: '2.1',
    notOperated: '3.other',
    held: '2.1',
    notHeldSimpleRent: '3.8',
    notHeldOther: '3.other',
  },
  {
    subPost: SubPost.Electricite,
    type: EmissionFactorPartType.TransportEtDistribution,
    operated: '3.3',
    notOperated: '3.other',
    held: '3.3',
    notHeldSimpleRent: '3.8',
    notHeldOther: '3.other',
  },
  {
    subPost: SubPost.Agriculture,
    operatedProcedeed: '1.3',
    operatedFugitive: '1.4',
    notOperated: '3.other',
    heldProcedeed: '1.3',
    heldFugitive: '1.4',
    notHeldSimpleRent: '3.8',
    notHeldOther: '3.other',
  },
  {
    subPost: SubPost.EmissionsLieesAuChangementDAffectationDesSolsCas,
    operated: '3.other',
    operatedProcedeed: '3.other',
    operatedFugitive: '3.other',
    notOperated: '3.other',
    held: '3.other',
    heldProcedeed: '3.other',
    heldFugitive: '3.other',
    notHeldSimpleRent: '3.8',
    notHeldOther: '3.other',
  },
  {
    subPost: SubPost.EmissionsLieesALaProductionDeFroid,
    operated: '1.4',
    operatedProcedeed: '1.4',
    operatedFugitive: '1.4',
    notOperated: '1.4',
    held: '1.4',
    heldProcedeed: '1.4',
    heldFugitive: '1.4',
    notHeldSimpleRent: '3.8',
    notHeldOther: '3.other',
  },
  {
    subPost: SubPost.EmissionsLieesAuxProcedesIndustriels,
    operated: '1.3',
    operatedProcedeed: '1.3',
    operatedFugitive: '1.3',
    notOperated: '1.3',
    held: '1.3',
    heldProcedeed: '1.3',
    heldFugitive: '1.3',
    notHeldSimpleRent: '3.8',
    notHeldOther: '3.other',
  },
  {
    subPost: SubPost.AutresEmissionsNonEnergetiques,
    operatedProcedeed: '1.3',
    operatedFugitive: '1.4',
    notOperated: '3.other',
    heldProcedeed: '1.3',
    heldFugitive: '1.4',
    notHeldSimpleRent: '3.8',
    notHeldOther: '3.other',
  },
  { subPost: SubPost.MetauxPlastiquesEtVerre, operated: '3.1', held: '3.1' },
  { subPost: SubPost.PapiersCartons, operated: '3.1', held: '3.1' },
  { subPost: SubPost.MateriauxDeConstruction, operated: '3.1', held: '3.1' },
  { subPost: SubPost.ProduitsChimiquesEtHydrogene, operated: '3.1', held: '3.1' },
  { subPost: SubPost.NourritureRepasBoissons, operated: '3.1', held: '3.1' },
  { subPost: SubPost.MatiereDestineeAuxEmballages, operated: '3.1', held: '3.1' },
  { subPost: SubPost.AutresIntrants, operated: '3.1', held: '3.1' },
  { subPost: SubPost.BiensEtMatieresEnApprocheMonetaire, operated: '3.1', held: '3.1' },

  { subPost: SubPost.AchatsDeServices, operated: '3.1', held: '3.1' },
  { subPost: SubPost.UsagesNumeriques, operated: '3.1', held: '3.1' },
  { subPost: SubPost.ServicesEnApprocheMonetaire, operated: '3.1', held: '3.1' },
  {
    subPost: SubPost.FretEntrant,
    operated: '1.2',
    notOperatedSupported: '3.4',
    notOperatedNotSupported: '4.09',
    held: '1.2',
    notHeldSupported: '3.4',
    notHeldNotSupported: '4.09',
  },
  {
    subPost: SubPost.FretEntrant,
    type: EmissionFactorPartType.Amont,
    operated: '3.3',
    notOperatedSupported: '3.4',
    notOperatedNotSupported: '4.09',
    held: '3.3',
    notHeldSupported: '3.4',
    notHeldNotSupported: '4.09',
  },
  {
    subPost: SubPost.FretEntrant,
    type: EmissionFactorPartType.Combustion,
    operated: '1.2',
    notOperatedSupported: '3.4',
    notOperatedNotSupported: '4.09',
    held: '1.2',
    notHeldSupported: '3.4',
    notHeldNotSupported: '4.09',
  },
  {
    subPost: SubPost.FretEntrant,
    type: EmissionFactorPartType.CombustionALaCentrale,
    operated: '2.1',
    notOperatedSupported: '3.4',
    notOperatedNotSupported: '4.09',
    held: '2.1',
    notHeldSupported: '3.4',
    notHeldNotSupported: '4.09',
  },
  {
    subPost: SubPost.FretEntrant,
    type: EmissionFactorPartType.EmissionsFugitives,
    operated: '1.4',
    notOperatedSupported: '3.4',
    notOperatedNotSupported: '4.09',
    held: '1.4',
    notHeldSupported: '3.4',
    notHeldNotSupported: '4.09',
  },
  {
    subPost: SubPost.FretEntrant,
    type: EmissionFactorPartType.Fabrication,
    operated: '4.2',
    notOperatedSupported: '3.4',
    notOperatedNotSupported: '4.09',
    held: '4.2',
    notHeldSupported: '3.4',
    notHeldNotSupported: '4.09',
  },
  {
    subPost: SubPost.FretInterne,
    operated: '1.2',
    notOperatedSupported: '3.4',
    notOperatedNotSupported: '4.09',
    held: '1.2',
    notHeldSupported: '3.4',
    notHeldNotSupported: '4.09',
  },
  {
    subPost: SubPost.FretInterne,
    type: EmissionFactorPartType.Amont,
    operated: '3.3',
    notOperatedSupported: '3.4',
    notOperatedNotSupported: '4.09',
    held: '3.3',
    notHeldSupported: '3.4',
    notHeldNotSupported: '4.09',
  },
  {
    subPost: SubPost.FretInterne,
    type: EmissionFactorPartType.Combustion,
    operated: '1.2',
    notOperatedSupported: '3.4',
    notOperatedNotSupported: '4.09',
    held: '1.2',
    notHeldSupported: '3.4',
    notHeldNotSupported: '4.09',
  },
  {
    subPost: SubPost.FretInterne,
    type: EmissionFactorPartType.CombustionALaCentrale,
    operated: '2.1',
    notOperatedSupported: '3.4',
    notOperatedNotSupported: '4.09',
    held: '2.1',
    notHeldSupported: '3.4',
    notHeldNotSupported: '4.09',
  },
  {
    subPost: SubPost.FretInterne,
    type: EmissionFactorPartType.EmissionsFugitives,
    operated: '1.4',
    notOperatedSupported: '3.4',
    notOperatedNotSupported: '4.09',
    held: '1.4',
    notHeldSupported: '3.4',
    notHeldNotSupported: '4.09',
  },
  {
    subPost: SubPost.FretInterne,
    type: EmissionFactorPartType.Fabrication,
    operated: '3.2',
    notOperatedSupported: '3.4',
    notOperatedNotSupported: '4.09',
    held: '3.2',
    notHeldSupported: '3.4',
    notHeldNotSupported: '4.09',
  },
  {
    subPost: SubPost.FretSortant,
    operated: '1.2',
    notOperatedSupported: '3.4',
    notOperatedNotSupported: '4.09',
    held: '1.2',
    notHeldSupported: '3.4',
    notHeldNotSupported: '4.09',
  },
  {
    subPost: SubPost.FretSortant,
    type: EmissionFactorPartType.Amont,
    operated: '3.3',
    notOperatedSupported: '3.4',
    notOperatedNotSupported: '4.09',
    held: '3.3',
    notHeldSupported: '3.4',
    notHeldNotSupported: '4.09',
  },
  {
    subPost: SubPost.FretSortant,
    type: EmissionFactorPartType.Combustion,
    operated: '1.2',
    notOperatedSupported: '3.4',
    notOperatedNotSupported: '4.09',
    held: '1.2',
    notHeldSupported: '3.4',
    notHeldNotSupported: '4.09',
  },
  {
    subPost: SubPost.FretSortant,
    type: EmissionFactorPartType.CombustionALaCentrale,
    operated: '2.1',
    notOperatedSupported: '3.4',
    notOperatedNotSupported: '4.09',
    held: '2.1',
    notHeldSupported: '3.4',
    notHeldNotSupported: '4.09',
  },
  {
    subPost: SubPost.FretSortant,
    type: EmissionFactorPartType.EmissionsFugitives,
    operated: '1.4',
    notOperatedSupported: '3.4',
    notOperatedNotSupported: '4.09',
    held: '1.4',
    notHeldSupported: '3.4',
    notHeldNotSupported: '4.09',
  },
  {
    subPost: SubPost.FretSortant,
    type: EmissionFactorPartType.Fabrication,
    operated: '3.2',
    notOperatedSupported: '3.4',
    notOperatedNotSupported: '4.09',
    held: '3.2',
    notHeldSupported: '3.4',
    notHeldNotSupported: '4.09',
  },
  {
    subPost: SubPost.DeplacementsDomicileTravail,
    operated: '1.2',
    notOperated: '3.7',
    held: '1.2',
    notHeldSimpleRent: '3.8',
    notHeldOther: '3.7',
  },
  {
    subPost: SubPost.DeplacementsDomicileTravail,
    type: EmissionFactorPartType.Amont,
    operated: '3.3',
    notOperated: '3.7',
    held: '3.3',
    notHeldSimpleRent: '3.8',
    notHeldOther: '3.7',
  },
  {
    subPost: SubPost.DeplacementsDomicileTravail,
    type: EmissionFactorPartType.Combustion,
    operated: '1.2',
    notOperated: '3.7',
    held: '1.2',
    notHeldSimpleRent: '3.8',
    notHeldOther: '3.7',
  },
  {
    subPost: SubPost.DeplacementsDomicileTravail,
    type: EmissionFactorPartType.CombustionALaCentrale,
    operated: '2.1',
    notOperated: '3.7',
    held: '2.1',
    notHeldSimpleRent: '3.8',
    notHeldOther: '3.7',
  },
  {
    subPost: SubPost.DeplacementsDomicileTravail,
    type: EmissionFactorPartType.EmissionsFugitives,
    operated: '1.4',
    notOperated: '3.7',
    held: '1.4',
    notHeldSimpleRent: '3.8',
    notHeldOther: '3.7',
  },
  {
    subPost: SubPost.DeplacementsDomicileTravail,
    type: EmissionFactorPartType.Fabrication,
    operated: '3.2',
    notOperated: '3.7',
    held: '3.2',
    notHeldSimpleRent: '3.8',
    notHeldOther: '3.7',
  },
  {
    subPost: SubPost.DeplacementsProfessionnels,
    operated: '1.2',
    notOperated: '3.6',
    held: '1.2',
    notHeldSimpleRent: '3.8',
    notHeldOther: '3.6',
  },
  {
    subPost: SubPost.DeplacementsProfessionnels,
    type: EmissionFactorPartType.Amont,
    operated: '3.3',
    notOperated: '3.6',
    held: '3.3',
    notHeldSimpleRent: '3.8',
    notHeldOther: '3.6',
  },
  {
    subPost: SubPost.DeplacementsProfessionnels,
    type: EmissionFactorPartType.Combustion,
    operated: '1.2',
    notOperated: '3.6',
    held: '1.2',
    notHeldSimpleRent: '3.8',
    notHeldOther: '3.6',
  },
  {
    subPost: SubPost.DeplacementsProfessionnels,
    type: EmissionFactorPartType.CombustionALaCentrale,
    operated: '2.1',
    notOperated: '3.6',
    held: '2.1',
    notHeldSimpleRent: '3.8',
    notHeldOther: '3.6',
  },
  {
    subPost: SubPost.DeplacementsProfessionnels,
    type: EmissionFactorPartType.EmissionsFugitives,
    operated: '1.4',
    notOperated: '3.6',
    held: '1.4',
    notHeldSimpleRent: '3.8',
    notHeldOther: '3.6',
  },
  {
    subPost: SubPost.DeplacementsProfessionnels,
    type: EmissionFactorPartType.Fabrication,
    operated: '3.2',
    notOperated: '3.6',
    held: '3.2',
    notHeldSimpleRent: '3.8',
    notHeldOther: '3.6',
  },
  {
    subPost: SubPost.DeplacementsVisiteurs,
    operated: '1.2',
    notOperated: '4.other',
    held: '1.2',
    notHeldSimpleRent: '3.8',
    notHeldOther: '4.other',
  },
  {
    subPost: SubPost.DeplacementsVisiteurs,
    type: EmissionFactorPartType.Amont,
    operated: '3.3',
    notOperated: '3.6',
    held: '3.3',
    notHeldSimpleRent: '3.8',
    notHeldOther: '3.6',
  },
  {
    subPost: SubPost.DeplacementsVisiteurs,
    type: EmissionFactorPartType.Combustion,
    operated: '1.2',
    notOperated: '3.6',
    held: '1.2',
    notHeldSimpleRent: '3.8',
    notHeldOther: '3.6',
  },
  {
    subPost: SubPost.DeplacementsVisiteurs,
    type: EmissionFactorPartType.CombustionALaCentrale,
    operated: '2.1',
    notOperated: '3.6',
    held: '2.1',
    notHeldSimpleRent: '3.8',
    notHeldOther: '3.6',
  },
  {
    subPost: SubPost.DeplacementsVisiteurs,
    type: EmissionFactorPartType.EmissionsFugitives,
    operated: '1.4',
    notOperated: '3.6',
    held: '1.4',
    notHeldSimpleRent: '3.8',
    notHeldOther: '3.6',
  },
  {
    subPost: SubPost.DeplacementsVisiteurs,
    type: EmissionFactorPartType.Fabrication,
    operated: '3.2',
    notOperated: '3.6',
    held: '3.2',
    notHeldSimpleRent: '3.8',
    notHeldOther: '3.6',
  },
  { subPost: SubPost.Batiments, operated: '3.2', held: '3.2' },
  { subPost: SubPost.AutresInfrastructures, operated: '3.2', held: '3.2' },
  { subPost: SubPost.Equipements, operated: '3.2', held: '3.2' },
  { subPost: SubPost.Informatique, operated: '3.2', held: '3.2' },
  { subPost: SubPost.DechetsDEmballagesEtPlastiques, operated: '3.5', held: '3.5' },
  { subPost: SubPost.DechetsOrganiques, operated: '3.5', held: '3.5' },
  { subPost: SubPost.DechetsOrduresMenageres, operated: '3.5', held: '3.5' },
  { subPost: SubPost.DechetsDangereux, operated: '3.5', held: '3.5' },
  { subPost: SubPost.DechetsBatiments, operated: '3.5', held: '3.5' },
  { subPost: SubPost.DechetsFuitesOuEmissionsNonEnergetiques, operated: '3.5', held: '3.5' },
  { subPost: SubPost.EauxUsees, operated: '3.5', held: '3.5' },
  { subPost: SubPost.AutresDechets, operated: '3.5', held: '3.5' },
  {
    subPost: SubPost.UtilisationEnResponsabilite,
    rented: '4.13',
    finalClient: '4.11',
    usedByIntermediary: '4.10',
  },
  { subPost: SubPost.UtilisationEnDependance, operated: '4.other', held: '4.other' },
  { subPost: SubPost.InvestissementsFinanciersRealises, operated: '4.15', held: '4.15' },
  { subPost: SubPost.ConsommationDEnergieEnFinDeVie, rented: '4.13', finalClient: '4.12', usedByIntermediary: '4.12' },
  { subPost: SubPost.TraitementDesDechetsEnFinDeVie, rented: '4.13', finalClient: '4.12', usedByIntermediary: '4.12' },
  {
    subPost: SubPost.FuitesOuEmissionsNonEnergetiques,
    rented: '4.13',
    finalClient: '4.12',
    usedByIntermediary: '4.12',
  },
  {
    subPost: SubPost.TraitementDesEmballagesEnFinDeVie,
    rented: '4.13',
    finalClient: '4.12',
    usedByIntermediary: '4.12',
  },
] satisfies Partial<ExportRule>[]
