describe('Real use case: BC V8_10', () => {
  beforeEach(() => {
    cy.exec('npx prisma db seed')
  })

  it('should correctly compute results', () => {
    cy.login()
    cy.visit('/etudes/91bb3826-2be7-4d56-bb9b-363f4d9af62f/comptabilisation/resultats')
    cy.getByTestId('consolidated-results-table-row')
      .eq(0)
      .within(() => {
        cy.get('td').eq(0).should('have.text', 'Autres émissions directes')
        cy.get('td').eq(2).should('have.text', '16\u202f660')
      })
    cy.getByTestId('consolidated-results-table-row')
      .eq(1)
      .within(() => {
        cy.get('td').eq(0).should('have.text', 'Déchets directs')
        cy.get('td').eq(2).should('have.text', '1\u202f858,23')
      })
    cy.getByTestId('consolidated-results-table-row')
      .eq(2)
      .within(() => {
        cy.get('td').eq(0).should('have.text', 'Déplacements')
        cy.get('td').eq(2).should('have.text', '105\u202f366,38')
      })
    cy.getByTestId('consolidated-results-table-row')
      .eq(3)
      .within(() => {
        cy.get('td').eq(0).should('have.text', 'Énergies')
        cy.get('td').eq(2).should('have.text', '15\u202f794,96')
      })
    cy.getByTestId('consolidated-results-table-row')
      .eq(4)
      .within(() => {
        cy.get('td').eq(0).should('have.text', 'Fin de vie')
        cy.get('td').eq(2).should('have.text', '6\u202f489')
      })
    cy.getByTestId('consolidated-results-table-row')
      .eq(5)
      .within(() => {
        cy.get('td').eq(0).should('have.text', 'Fret')
        cy.get('td').eq(2).should('have.text', '4\u202f328,49')
      })
    cy.getByTestId('consolidated-results-table-row')
      .eq(6)
      .within(() => {
        cy.get('td').eq(0).should('have.text', 'Immobilisations')
        cy.get('td').eq(2).should('have.text', '11\u202f554,56')
      })
    cy.getByTestId('consolidated-results-table-row')
      .eq(7)
      .within(() => {
        cy.get('td').eq(0).should('have.text', 'Intrants biens et matières')
        cy.get('td').eq(2).should('have.text', '16\u202f540,9')
      })
    cy.getByTestId('consolidated-results-table-row')
      .eq(8)
      .within(() => {
        cy.get('td').eq(0).should('have.text', 'Intrants services')
        cy.get('td').eq(2).should('have.text', '103\u202f744,35')
      })
    cy.getByTestId('consolidated-results-table-row')
      .eq(9)
      .within(() => {
        cy.get('td').eq(0).should('have.text', 'Utilisation et dépendance')
        cy.get('td').eq(2).should('have.text', '0')
      })
    cy.getByTestId('consolidated-results-table-row')
      .eq(10)
      .within(() => {
        cy.get('td').eq(0).should('have.text', 'Total')
        cy.get('td').eq(2).should('have.text', '282\u202f336,86')
      })

    cy.getByTestId('result-type-select').click()
    cy.get('[data-value="Beges"]').click()

    cy.getByTestId('beges-results-table-row')
      .eq(0)
      .within(() => {
        cy.get('td').eq(2).should('have.text', '3990')
        cy.get('td').eq(3).should('have.text', '2.97')
        cy.get('td').eq(4).should('have.text', '21.75')
        cy.get('td').eq(5).should('have.text', '0')
        cy.get('td').eq(6).should('have.text', '4014.7200000000003')
        cy.get('td').eq(7).should('have.text', '33949.3865')
      })
    cy.getByTestId('beges-results-table-row')
      .eq(1)
      .within(() => {
        cy.get('td').eq(1).should('have.text', '37847.6')
        cy.get('td').eq(2).should('have.text', '0')
        cy.get('td').eq(3).should('have.text', '0')
        cy.get('td').eq(4).should('have.text', '0')
        cy.get('td').eq(5).should('have.text', '37847.6')
        cy.get('td').eq(6).should('have.text', '0')
      })
    cy.getByTestId('beges-results-table-row')
      .eq(2)
      .within(() => {
        cy.get('td').eq(1).should('have.text', '0')
        cy.get('td').eq(2).should('have.text', '0')
        cy.get('td').eq(3).should('have.text', '0')
        cy.get('td').eq(4).should('have.text', '0')
        cy.get('td').eq(5).should('have.text', '0')
        cy.get('td').eq(6).should('have.text', '0')
      })
    cy.getByTestId('beges-results-table-row')
      .eq(3)
      .within(() => {
        cy.get('td').eq(1).should('have.text', '16660')
        cy.get('td').eq(2).should('have.text', '0')
        cy.get('td').eq(3).should('have.text', '0')
        cy.get('td').eq(4).should('have.text', '0')
        cy.get('td').eq(5).should('have.text', '16660')
        cy.get('td').eq(6).should('have.text', '0')
      })
    cy.getByTestId('beges-results-table-row')
      .eq(4)
      .within(() => {
        cy.get('td').eq(1).should('have.text', '0')
        cy.get('td').eq(2).should('have.text', '0')
        cy.get('td').eq(3).should('have.text', '0')
        cy.get('td').eq(4).should('have.text', '0')
        cy.get('td').eq(5).should('have.text', '0')
        cy.get('td').eq(6).should('have.text', '0')
      })
    cy.getByTestId('beges-results-table-row')
      .eq(5)
      .within(() => {
        cy.get('td').eq(1).should('have.text', '58497.6')
        cy.get('td').eq(2).should('have.text', '2.97')
        cy.get('td').eq(3).should('have.text', '21.75')
        cy.get('td').eq(4).should('have.text', '0')
        cy.get('td').eq(5).should('have.text', '58522.32')
        cy.get('td').eq(6).should('have.text', '33949.3865')
      })
    cy.getByTestId('beges-results-table-row')
      .eq(6)
      .within(() => {
        cy.get('td').eq(2).should('have.text', '5610.799999999999')
        cy.get('td').eq(3).should('have.text', '0')
        cy.get('td').eq(4).should('have.text', '0')
        cy.get('td').eq(5).should('have.text', '0')
        cy.get('td').eq(6).should('have.text', '5610.799999999999')
        cy.get('td').eq(7).should('have.text', '0')
      })
    cy.getByTestId('beges-results-table-row')
      .eq(7)
      .within(() => {
        cy.get('td').eq(1).should('have.text', '0')
        cy.get('td').eq(2).should('have.text', '0')
        cy.get('td').eq(3).should('have.text', '0')
        cy.get('td').eq(4).should('have.text', '0')
        cy.get('td').eq(5).should('have.text', '0')
        cy.get('td').eq(6).should('have.text', '0')
      })
    cy.getByTestId('beges-results-table-row')
      .eq(8)
      .within(() => {
        cy.get('td').eq(1).should('have.text', '5610.799999999999')
        cy.get('td').eq(2).should('have.text', '0')
        cy.get('td').eq(3).should('have.text', '0')
        cy.get('td').eq(4).should('have.text', '0')
        cy.get('td').eq(5).should('have.text', '5610.799999999999')
        cy.get('td').eq(6).should('have.text', '0')
      })
    cy.getByTestId('beges-results-table-row')
      .eq(9)
      .within(() => {
        cy.get('td').eq(2).should('have.text', '1492.09368')
        cy.get('td').eq(3).should('have.text', '0')
        cy.get('td').eq(4).should('have.text', '0')
        cy.get('td').eq(5).should('have.text', '0')
        cy.get('td').eq(6).should('have.text', '1492.09368')
        cy.get('td').eq(7).should('have.text', '0')
      })
    cy.getByTestId('beges-results-table-row')
      .eq(10)
      .within(() => {
        cy.get('td').eq(1).should('have.text', '0')
        cy.get('td').eq(2).should('have.text', '0')
        cy.get('td').eq(3).should('have.text', '0')
        cy.get('td').eq(4).should('have.text', '0')
        cy.get('td').eq(5).should('have.text', '0')
        cy.get('td').eq(6).should('have.text', '0')
      })
    cy.getByTestId('beges-results-table-row')
      .eq(11)
      .within(() => {
        cy.get('td').eq(1).should('have.text', '48646.17556')
        cy.get('td').eq(2).should('have.text', '0')
        cy.get('td').eq(3).should('have.text', '0')
        cy.get('td').eq(4).should('have.text', '0')
        cy.get('td').eq(5).should('have.text', '48646.17556')
        cy.get('td').eq(6).should('have.text', '0')
      })
    cy.getByTestId('beges-results-table-row')
      .eq(12)
      .within(() => {
        cy.get('td').eq(1).should('have.text', '0')
        cy.get('td').eq(2).should('have.text', '0')
        cy.get('td').eq(3).should('have.text', '0')
        cy.get('td').eq(4).should('have.text', '0')
        cy.get('td').eq(5).should('have.text', '0')
        cy.get('td').eq(6).should('have.text', '0')
      })
    cy.getByTestId('beges-results-table-row')
      .eq(13)
      .within(() => {
        cy.get('td').eq(1).should('have.text', '2013.91')
        cy.get('td').eq(2).should('have.text', '4.70295')
        cy.get('td').eq(3).should('have.text', '9.108')
        cy.get('td').eq(4).should('have.text', '526.5')
        cy.get('td').eq(5).should('have.text', '2554.2209500000004')
        cy.get('td').eq(6).should('have.text', '0')
      })
    cy.getByTestId('beges-results-table-row')
      .eq(14)
      .within(() => {
        cy.get('td').eq(1).should('have.text', '52152.179240000005')
        cy.get('td').eq(2).should('have.text', '4.70295')
        cy.get('td').eq(3).should('have.text', '9.108')
        cy.get('td').eq(4).should('have.text', '526.5')
        cy.get('td').eq(5).should('have.text', '52692.490190000004')
        cy.get('td').eq(6).should('have.text', '0')
      })
    cy.getByTestId('beges-results-table-row')
      .eq(15)
      .within(() => {
        cy.get('td').eq(2).should('have.text', '31823.4269')
        cy.get('td').eq(3).should('have.text', '72')
        cy.get('td').eq(4).should('have.text', '0')
        cy.get('td').eq(5).should('have.text', '0')
        cy.get('td').eq(6).should('have.text', '31895.4269')
        cy.get('td').eq(7).should('have.text', '-33949.3865')
      })
    cy.getByTestId('beges-results-table-row')
      .eq(16)
      .within(() => {
        cy.get('td').eq(1).should('have.text', '21524.24792857143')
        cy.get('td').eq(2).should('have.text', '0')
        cy.get('td').eq(3).should('have.text', '0')
        cy.get('td').eq(4).should('have.text', '0')
        cy.get('td').eq(5).should('have.text', '21524.24792857143')
        cy.get('td').eq(6).should('have.text', '0')
      })
    cy.getByTestId('beges-results-table-row')
      .eq(17)
      .within(() => {
        cy.get('td').eq(1).should('have.text', '1805.02')
        cy.get('td').eq(2).should('have.text', '52.800000000000004')
        cy.get('td').eq(3).should('have.text', '0.40800000000000003')
        cy.get('td').eq(4).should('have.text', '0')
        cy.get('td').eq(5).should('have.text', '1858.228')
        cy.get('td').eq(6).should('have.text', '68.94190934')
      })
    cy.getByTestId('beges-results-table-row')
      .eq(18)
      .within(() => {
        cy.get('td').eq(1).should('have.text', '0')
        cy.get('td').eq(2).should('have.text', '0')
        cy.get('td').eq(3).should('have.text', '0')
        cy.get('td').eq(4).should('have.text', '0')
        cy.get('td').eq(5).should('have.text', '0')
        cy.get('td').eq(6).should('have.text', '0')
      })
    cy.getByTestId('beges-results-table-row')
      .eq(19)
      .within(() => {
        cy.get('td').eq(1).should('have.text', '103744.347')
        cy.get('td').eq(2).should('have.text', '0')
        cy.get('td').eq(3).should('have.text', '0')
        cy.get('td').eq(4).should('have.text', '0')
        cy.get('td').eq(5).should('have.text', '103744.347')
        cy.get('td').eq(6).should('have.text', '0')
      })
    cy.getByTestId('beges-results-table-row')
      .eq(20)
      .within(() => {
        cy.get('td').eq(1).should('have.text', '158897.0418285714')
        cy.get('td').eq(2).should('have.text', '124.80000000000001')
        cy.get('td').eq(3).should('have.text', '0.40800000000000003')
        cy.get('td').eq(4).should('have.text', '0')
        cy.get('td').eq(5).should('have.text', '159022.24982857142')
        cy.get('td').eq(6).should('have.text', '-33880.44459066')
      })
    cy.getByTestId('beges-results-table-row')
      .eq(21)
      .within(() => {
        cy.get('td').eq(2).should('have.text', '0')
        cy.get('td').eq(3).should('have.text', '0')
        cy.get('td').eq(4).should('have.text', '0')
        cy.get('td').eq(5).should('have.text', '0')
        cy.get('td').eq(6).should('have.text', '0')
        cy.get('td').eq(7).should('have.text', '0')
      })
    cy.getByTestId('beges-results-table-row')
      .eq(22)
      .within(() => {
        cy.get('td').eq(1).should('have.text', '0')
        cy.get('td').eq(2).should('have.text', '0')
        cy.get('td').eq(3).should('have.text', '0')
        cy.get('td').eq(4).should('have.text', '0')
        cy.get('td').eq(5).should('have.text', '0')
        cy.get('td').eq(6).should('have.text', '0')
      })
    cy.getByTestId('beges-results-table-row')
      .eq(23)
      .within(() => {
        cy.get('td').eq(1).should('have.text', '5774')
        cy.get('td').eq(2).should('have.text', '710')
        cy.get('td').eq(3).should('have.text', '5')
        cy.get('td').eq(4).should('have.text', '0')
        cy.get('td').eq(5).should('have.text', '6489')
        cy.get('td').eq(6).should('have.text', '862.5')
      })
    cy.getByTestId('beges-results-table-row')
      .eq(24)
      .within(() => {
        cy.get('td').eq(1).should('have.text', '0')
        cy.get('td').eq(2).should('have.text', '0')
        cy.get('td').eq(3).should('have.text', '0')
        cy.get('td').eq(4).should('have.text', '0')
        cy.get('td').eq(5).should('have.text', '0')
        cy.get('td').eq(6).should('have.text', '0')
      })
    cy.getByTestId('beges-results-table-row')
      .eq(25)
      .within(() => {
        cy.get('td').eq(1).should('have.text', '5774')
        cy.get('td').eq(2).should('have.text', '710')
        cy.get('td').eq(3).should('have.text', '5')
        cy.get('td').eq(4).should('have.text', '0')
        cy.get('td').eq(5).should('have.text', '6489')
        cy.get('td').eq(6).should('have.text', '862.5')
      })
    cy.getByTestId('beges-results-table-row')
      .eq(26)
      .within(() => {
        cy.get('td').eq(2).should('have.text', '0')
        cy.get('td').eq(3).should('have.text', '0')
        cy.get('td').eq(4).should('have.text', '0')
        cy.get('td').eq(5).should('have.text', '0')
        cy.get('td').eq(6).should('have.text', '0')
        cy.get('td').eq(7).should('have.text', '0')
      })
    cy.getByTestId('beges-results-table-row')
      .eq(27)
      .within(() => {
        cy.get('td').eq(1).should('have.text', '0')
        cy.get('td').eq(2).should('have.text', '0')
        cy.get('td').eq(3).should('have.text', '0')
        cy.get('td').eq(4).should('have.text', '0')
        cy.get('td').eq(5).should('have.text', '0')
        cy.get('td').eq(6).should('have.text', '0')
      })
    cy.getByTestId('beges-results-table-row')
      .eq(28)
      .within(() => {
        cy.get('td').eq(2).should('have.text', '280931.6210685714')
        cy.get('td').eq(3).should('have.text', '842.47295')
        cy.get('td').eq(4).should('have.text', '36.266000000000005')
        cy.get('td').eq(5).should('have.text', '526.5')
        cy.get('td').eq(6).should('have.text', '282336.86001857143')
        cy.get('td').eq(7).should('have.text', '931.4419093399999')
      })
  })
})
