import { getEmissionFactorsFromCSV } from '@/services/baseEmpreinte/getEmissionFactorsFromCSV'
import {
  ControlMode,
  EmissionSourceCaracterisation,
  Export,
  Import,
  Level,
  PrismaClient,
  SubPost,
  User,
} from '@prisma/client'

export const createRealStudy = async (prisma: PrismaClient, creator: User) => {
  if (!creator.organizationId) {
    return null
  }

  await getEmissionFactorsFromCSV('test', './prisma/seed/Base_Carbone_Test.csv')

  await prisma.site.create({
    data: {
      id: 'c3f2b8d4-7a0c-4b3f-8c5b-5b5e7b6f3e3b',
      name: 'Bourges',
      organizationId: creator.organizationId,
      etp: 35,
      ca: 1_000_000,
    },
  })

  const version = await prisma.emissionFactorImportVersion.findFirst({
    where: { internId: 'Base_Carbone_Test.csv', source: Import.BaseEmpreinte },
  })
  if (!version) {
    return null
  }

  const emissionFactors = await prisma.emissionFactor.findMany({
    where: { versionId: version.id },
  })

  await prisma.study.create({
    data: {
      id: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
      name: 'BC V8.10',
      startDate: new Date('2025-01-01'),
      endDate: new Date('2025-12-31'),
      isPublic: true,
      level: Level.Initial,
      exports: { createMany: { data: [{ type: Export.Beges, control: ControlMode.Operational }] } },
      createdBy: { connect: { id: creator.id } },
      organization: { connect: { id: creator.organizationId } },
      version: { connect: { id: version.id } },
      sites: {
        createMany: {
          data: [
            {
              id: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
              siteId: 'c3f2b8d4-7a0c-4b3f-8c5b-5b5e7b6f3e3b',
              etp: 35,
              ca: 1_000_000,
            },
          ],
        },
      },
    },
  })

  await prisma.studyEmissionSource.createMany({
    data: [
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: 'Fioul domestique, France continentale, Base Carbone',
        subPost: SubPost.CombustiblesFossiles,
        caracterisation: EmissionSourceCaracterisation.Operated,
        value: 1500,
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '14087')?.id,
      },
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: 'Plaquettes forestières sèches (25% humidité), France continentale, Base Carbone',
        subPost: SubPost.CombustiblesOrganiques,
        caracterisation: EmissionSourceCaracterisation.Operated,
        value: 25000,
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '34943')?.id,
      },
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: '2022 - mix moyen, France continentale, Base Carbone',
        subPost: SubPost.Electricite,
        caracterisation: EmissionSourceCaracterisation.Operated,
        value: 166000,
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '42513')?.id,
      },
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: 'photovoltaïque - fabrication Europe, France continentale, Base Carbone',
        subPost: SubPost.Electricite,
        caracterisation: EmissionSourceCaracterisation.Operated,
        value: 32000,
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '34721')?.id,
      },
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: 'R22 (HCFC-22), Base Carbone',
        subPost: SubPost.AutresEmissionsNonEnergetiques,
        value: 9,
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '43119')?.id,
      },
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: 'Action sociale, France continentale, Base Carbone',
        subPost: SubPost.ServicesEnApprocheMonetaire,
        value: 1.50824,
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '25029')?.id,
      },
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: 'Activités des organisations associatives, France continentale, Base Carbone',
        subPost: SubPost.ServicesEnApprocheMonetaire,
        value: 2.4,
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '25032')?.id,
      },
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: 'Assurance, services bancaires, conseil et honoraires, France continentale, Base Carbone',
        subPost: SubPost.ServicesEnApprocheMonetaire,
        value: 10.21678,
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '24997')?.id,
      },
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: 'Courrier, France continentale, Base Carbone',
        subPost: SubPost.ServicesEnApprocheMonetaire,
        value: 1.45,
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '24998')?.id,
      },
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: 'Enseignement, France continentale, Base Carbone',
        subPost: SubPost.ServicesEnApprocheMonetaire,
        value: 13.1,
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '25026')?.id,
      },
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: 'Hébergement et restauration, France continentale, Base Carbone',
        subPost: SubPost.ServicesEnApprocheMonetaire,
        value: 19.18852,
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '25000')?.id,
      },
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: 'Machines et équipements, France continentale, Base Carbone',
        subPost: SubPost.ServicesEnApprocheMonetaire,
        value: 10.53958,
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '25022')?.id,
      },
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: 'Meubles et autres biens manufacturés, France continentale, Base Carbone',
        subPost: SubPost.ServicesEnApprocheMonetaire,
        value: 7.04136,
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '25017')?.id,
      },
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: 'Produits chimiques, France continentale, Base Carbone',
        subPost: SubPost.ServicesEnApprocheMonetaire,
        value: 3.136,
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '25018')?.id,
      },
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: "Réparation et installation de machines et d'équipements, France continentale, Base Carbone",
        subPost: SubPost.ServicesEnApprocheMonetaire,
        value: 3.36466,
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '25004')?.id,
      },
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: 'Services (imprimerie, publicité, architecture et ingénierie, maintenance multi-technique des bâtimen, France continentale, Base Carbone',
        subPost: SubPost.ServicesEnApprocheMonetaire,
        value: 294.04176,
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '25001')?.id,
      },
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: 'Télécommunications, France continentale, Base Carbone',
        subPost: SubPost.ServicesEnApprocheMonetaire,
        value: 142.65466,
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '24999')?.id,
      },
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: 'Transport terrestre, France continentale, Base Carbone',
        subPost: SubPost.ServicesEnApprocheMonetaire,
        value: 3.3395,
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '25005')?.id,
      },
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: 'Acier ou fer blanc, France continentale, Base Carbone',
        subPost: SubPost.MetauxPlastiquesEtVerre,
        value: 0.18,
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '26729')?.id,
      },
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: 'Acier ou fer blanc, France continentale, Base Carbone - Fin de vie',
        subPost: SubPost.MetauxPlastiquesEtVerre,
        value: 0.18,
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '34462')?.id,
      },
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: 'Films plastiques PET (pas recyclable), France continentale, Base Carbone',
        subPost: SubPost.MetauxPlastiquesEtVerre,
        value: 2.5,
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '20835')?.id,
      },
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: 'Films plastiques PET (pas recyclable), France continentale, Base Carbone - Fin de vie',
        subPost: SubPost.MetauxPlastiquesEtVerre,
        value: 2.5,
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '34496')?.id,
      },
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: 'Bois courte durée de vie (ameublement…) fabrication, France continentale, Base Carbone',
        subPost: SubPost.PapiersCartons,
        value: 3,
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '20908')?.id,
      },
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: 'Bois courte durée de vie (ameublement…) fabrication, France continentale, Base Carbone - Fin de vie',
        subPost: SubPost.PapiersCartons,
        value: 3,
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '34478')?.id,
      },
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: 'Papier Moyen, Hors utilisation et fin de vie, France continentale, Base Carbone',
        subPost: SubPost.PapiersCartons,
        value: 3000,
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '24309')?.id,
      },
      // Manque la fin de vie du papier moyenne
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: 'Carton - Fin de vie moyenne filière - impacts, France continentale, Base Carbone',
        subPost: SubPost.DechetsDEmballagesEtPlastiques,
        value: 1.3,
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '34486')?.id,
      },
      // Manque Papier/fin de vie moyenne, France continentale, Base Carbone
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: 'Plastique souple PET pétrosourcé - Fin de vie moyenne filière - Impacts, France continentale, Base Carbone',
        subPost: SubPost.DechetsDEmballagesEtPlastiques,
        value: 0.5,
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '34512')?.id,
      },
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: 'Articulé, 34 à 40 T, diesel routier, 7% de biodiesel, France continentale, Base Carbone',
        subPost: SubPost.FretEntrant,
        caracterisation: EmissionSourceCaracterisation.NotOperatedNotSupported,
        value: 3668,
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '28041')?.id,
      },
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: 'Articulé, 34 à 40 T, diesel routier, 7% de biodiesel, France continentale, Base Carbone',
        subPost: SubPost.FretSortant,
        caracterisation: EmissionSourceCaracterisation.Operated,
        value: 34400,
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '28041')?.id,
      },
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: 'Rigide, 12 à 20 T, diesel routier, 7% biodiesel, France continentale, Base Carbone',
        subPost: SubPost.FretSortant,
        caracterisation: EmissionSourceCaracterisation.Operated,
        value: 33,
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '28033')?.id,
      },
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: 'Porte-conteneurs, Dry, Europe - Afrique, France continentale, Base Carbone',
        subPost: SubPost.FretSortant,
        caracterisation: EmissionSourceCaracterisation.NotOperatedNotSupported,
        value: 10387,
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '28205')?.id,
      },
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: 'Porte-conteneurs, Dry, Europe - Amérique du Sud et Centrale, France continentale, Base Carbone',
        subPost: SubPost.FretSortant,
        caracterisation: EmissionSourceCaracterisation.NotOperatedNotSupported,
        value: 38191,
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '28207')?.id,
      },
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: 'Porte-conteneurs, Dry, Europe du Nord - Amérique du Nord, façade atlantique, France continentale, Base Carbone',
        subPost: SubPost.FretSortant,
        caracterisation: EmissionSourceCaracterisation.NotOperatedNotSupported,
        value: 0,
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '28218')?.id,
      },
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: 'Porte-conteneurs, Dry, Europe - Océanie, France continentale, Base Carbone',
        subPost: SubPost.FretSortant,
        caracterisation: EmissionSourceCaracterisation.NotOperatedNotSupported,
        value: 41424,
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '28211')?.id,
      },
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: 'Porte-conteneurs, Dry, Intra Méditerranée, France continentale, Base Carbone',
        subPost: SubPost.FretSortant,
        caracterisation: EmissionSourceCaracterisation.NotOperatedNotSupported,
        value: 3000,
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '28225')?.id,
      },
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: 'Porte-conteneurs, Dry, Asie - Europe du Nord, France continentale, Base Carbone',
        subPost: SubPost.FretSortant,
        caracterisation: EmissionSourceCaracterisation.NotOperatedNotSupported,
        value: 35685,
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '28203')?.id,
      },
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: 'Voiture - motorisation essence - 2018, France continentale, Base Carbone',
        subPost: SubPost.DeplacementsDomicileTravail,
        caracterisation: EmissionSourceCaracterisation.NotOperated,
        value: 90339,
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '27965')?.id,
      },
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: 'Voiture - motorisation gazole - 2018, France continentale, Base Carbone',
        subPost: SubPost.DeplacementsDomicileTravail,
        caracterisation: EmissionSourceCaracterisation.NotOperated,
        value: 106362,
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '27966')?.id,
      },
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: 'Voiture particulière - cœur de gamme - véhicule compact - électrique, France continentale, Base Carbone',
        subPost: SubPost.DeplacementsDomicileTravail,
        caracterisation: EmissionSourceCaracterisation.NotOperated,
        value: 5494,
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '28007')?.id,
      },
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: 'Autobus moyen - agglomération de 100 000 à 250 000 habitants, France continentale, Base Carbone',
        subPost: SubPost.DeplacementsDomicileTravail,
        caracterisation: EmissionSourceCaracterisation.NotOperated,
        value: 8240,
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '27999')?.id,
      },
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: 'Métro, tramway, trolleybus - 2018 - Agglomération de 100 000 à 250 000 habitants, France continentale, Base Carbone',
        subPost: SubPost.DeplacementsDomicileTravail,
        caracterisation: EmissionSourceCaracterisation.NotOperated,
        value: 2289,
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '28150')?.id,
      },
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: 'TER - 2021 - traction moyenne, France continentale, Base Carbone',
        subPost: SubPost.DeplacementsDomicileTravail,
        caracterisation: EmissionSourceCaracterisation.NotOperated,
        value: 34335,
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '37141')?.id,
      },
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: 'Voiture - motorisation essence - 2018, France continentale, Base Carbone',
        subPost: SubPost.DeplacementsDesEmployesDansLeCadreDuTravail,
        caracterisation: EmissionSourceCaracterisation.Operated,
        value: 16500,
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '27965')?.id,
      },
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: 'Voiture - motorisation gazole - 2018, France continentale, Base Carbone',
        subPost: SubPost.DeplacementsDesEmployesDansLeCadreDuTravail,
        caracterisation: EmissionSourceCaracterisation.Operated,
        value: 220000,
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '27966')?.id,
      },
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: 'Voiture particulière - cœur de gamme - véhicule compact - électrique, France continentale, Base Carbone',
        subPost: SubPost.DeplacementsDesEmployesDansLeCadreDuTravail,
        caracterisation: EmissionSourceCaracterisation.Operated,
        value: 1700,
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '28007')?.id,
      },
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: 'Intercités - 2019, France continentale, Base Carbone',
        subPost: SubPost.DeplacementsDesEmployesDansLeCadreDuTravail,
        caracterisation: EmissionSourceCaracterisation.NotOperated,
        value: 235000,
        // J'ai pas l'intercité 2019
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '37144')?.id,
      },
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: 'Avion passagers, court courrier, avec trainées, France continentale, Base Carbone',
        subPost: SubPost.DeplacementsDesEmployesDansLeCadreDuTravail,
        caracterisation: EmissionSourceCaracterisation.NotOperated,
        value: 4500,
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '28130')?.id,
      },
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: 'Bâtiment industriel, structure métallique, France continentale, Base Carbone',
        subPost: SubPost.Batiments,
        value: 750,
        // Que fait on du par année ?
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '20731')?.id,
      },
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: 'Parking, classique - bitume, France continentale, Base Carbone',
        subPost: SubPost.Batiments,
        value: 500,
        // Que fait on du par année ?
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '26011')?.id,
      },
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: 'Machines, France continentale, Base Carbone',
        // Bon poste ?
        subPost: SubPost.AutresInfrastructures,
        value: 2000,
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '20906')?.id,
      },
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: 'Mobilier, France continentale, Base Carbone',
        subPost: SubPost.AutresInfrastructures,
        value: 2,
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '20907')?.id,
      },
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: 'Ordinateur portable, France continentale, Base Carbone',
        subPost: SubPost.Informatique,
        value: 15,
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '27002')?.id,
      },
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: 'Ordinateur fixe - bureautique, France continentale, Base Carbone',
        subPost: SubPost.Informatique,
        value: 10,
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '27003')?.id,
      },
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: "Imprimante jet d'encre, France continentale, Base Carbone",
        subPost: SubPost.Informatique,
        value: 5,
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '27025')?.id,
      },
      {
        studyId: '91bb3826-2be7-4d56-bb9b-363f4d9af62f',
        siteId: 'ca3e68bd-dee6-400a-b3cb-b3e11725282e',
        reliability: 1,
        name: 'Photocopieurs, Monde, Base Carbone',
        subPost: SubPost.Informatique,
        value: 2,
        emissionFactorId: emissionFactors.find((emissionFactor) => emissionFactor.importedId === '20591')?.id,
      },
    ],
  })
}
